### ISSUE TITLE
Question: would you consider adding this library to the Janet pkgs

### ISSUE THREAD

**Issue by pepe** [dabeaz/ranet#1]
Hello. 

I am the new co-maintainer of [Janet packages repository](https://github.com/janet-lang/pkgs). I found your library a good fit for the repository, and I would like to ask if you consider adding it to pkgs? 

There are [contributing guidelines](https://github.com/janet-lang/pkgs/blob/master/CONTRIBUTING.md), as I saw your code lacks the `project.janet` file. A good example of it could be found [here](https://github.com/MikeBeller/janet-set/blob/main/project.janet).

Please feel free to ask me anything you would like to know or ignore this request at all.

**Comment by pepe** [comment]
I understand you have no desire for this, so that I will close it.

**Comment by dabeaz** [comment]
I apologize for missing this the first time---running a business, kids, pandemic, and now a puppy.

As much as I appreciate having this in packages, this is purely an educational project for me (basically, a first Janet program).  Also, Raft is notoriously difficult to implement due to its large number of edge cases and other matters.  As such, I don't have a high degree of confidence in the robustness of the code appearing here--certainly not to a point of wanting to support it as any kind of official package or implementation of Raft.    The main purpose of publishing it here, again, is purely educational.  It might be an interesting example of concurrency, networks, and Janet.

I like Janet though... if I make other projects, I'll consider adding them to packages.

**Comment by pepe** [comment]
Great to hear you like Janet. For the time constraints, I can fully understand as a father of three and master of two (one just leaving puppy age).

I know very little about Raft's advanced issues, so I take your word on this. My question was based on the need I have in this field.

If you in the future need any assistance with Janet's packages, please feel free to contact me.
